### ISSUE TITLE
一些问题反馈

### ISSUE THREAD

**Issue by link26283** [yhnmj6666/NewThunderCross#1]
感谢作者写这个召唤迅雷的插件。该插件基本上能够满足需求，但在使用中发现一个小问题，反馈给作者：
在每次关闭浏览器后重新打开的时候都会弹出一个下载提示框，就是最后一次下载的文件，每次重新打开浏览器都会弹一次，希望作者能够解决，再次感谢。

**Comment by yhnmj6666** [comment]
你好,这个问题emmmm有点迷.有可能是插件之间的相互冲突吗?
