### ISSUE TITLE
文件名出现乱码

### ISSUE THREAD

**Issue by Greedysky** [yhnmj6666/NewThunderCross#10]
如图:
![qq 20180201174605](https://user-images.githubusercontent.com/7044256/35671966-e881e916-0777-11e8-8cbf-e910c634e434.png)

**Comment by Greedysky** [comment]
环境 Win10 58.0.1 (32 位)

**Comment by yhnmj6666** [comment]
情况已经知道了，百度云传来的就是这个，之后我研究一下怎么解

**Comment by yhnmj6666** [comment]
fixed in v0.2.5
