### ISSUE TITLE
为什么语言多了 hant 跟 hans ?

### ISSUE THREAD

**Issue by zhtw2013** [yhnmj6666/NewThunderCross#11]
这不是跟 zh-TW、zh-CN 重复了吗？
而且維護起來也不方便吧？

**Comment by yhnmj6666** [comment]
嗯...说实话我不是很清楚中文的繁体到底要用什么..而且Hans跟Hant的兼容性好像也不怎么样,暂时不管他吧

**Comment by zhtw2013** [comment]
你这样要维护两份啊..
浏览器应该是没有分别的吧..都是用zh_TW(繁体)、zh_CN(简体)

不过Android上是有分别的，Hant跟zh_TW分属不同的语言

**Comment by yhnmj6666** [comment]
好的,那我把hans跟hant去掉吧.谢谢!
