### ISSUE TITLE
爱奇艺跳出一堆下载框 

### ISSUE THREAD

**Issue by Greedysky** [yhnmj6666/NewThunderCross#13]
在看爱奇艺视频（广告等待）的时候，会弹出一堆下载框 。

**Comment by yhnmj6666** [comment]
好的，下个版本修复
不过不是很清楚怎么修复23333
要不做成去广告功能吧2333
还是顺其自然好了2333

**Comment by yhnmj6666** [comment]
fixed by adding non-detect extension
