### ISSUE TITLE
安装问题

### ISSUE THREAD

**Issue by stanz2g** [yhnmj6666/NewThunderCross#15]
环境：win10 pro x64
版本：0.2.6
问题描述：
在0.2.5版本正确安装的情况下
1、将thundercross程序替换为0.2.6版本
2、运行程序，只能得到“是否安装”对话框而不能得到预期的卸载对话框。即使选“是”执行安装操作，之后再运行也是相同现象
3、然后尝试删除thundercross.json再运行程序，弹出卸载对话框。点“是”后提示卸载成功
4、再次运行程序，仍弹出卸载对话框而不是预期的安装对话框，点“是”后抛如下异常。再反复运行也是相同现象
未经处理的异常:  System.ArgumentException: 该子项不存在，因此无法删除子项目录树。
   在 System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   在 Microsoft.Win32.RegistryKey.DeleteSubKey(String subkey, Boolean throwOnMissingSubKey)
   在 ThunderCross.Program.Uninstalltion()
   在 ThunderCross.Program.Main(String[] args)

**Comment by yhnmj6666** [comment]
抱歉手滑了emmm已经改好啦
