### ISSUE TITLE
机锋论坛跳出一堆下载框

### ISSUE THREAD

**Issue by Jerry-1984** [yhnmj6666/NewThunderCross#5]
http://bbs.gfan.com/forum-62-1.html，这个网址，打开就弹出十几个下载框，系统Win7X64,FX最新Nightly59.0a1 32位
![1](https://user-images.githubusercontent.com/31561637/34199522-04489000-e5a9-11e7-8559-2d40eb4b56d0.jpg)

**Comment by yhnmj6666** [comment]
已修复,待更新
