### ISSUE TITLE
下载页面被跳转成空页面

### ISSUE THREAD

**Issue by stanz2g** [yhnmj6666/NewThunderCross#8]
版本：2.2@FF57.0.4
操作：在网页点击一个下载链接，弹出thundercross对话框，然后点击确定或取消
期望结果：原网页不受影响，最多会残留一个新标签页moz-extension://064ac6c9-374a-49b2-b407-a53683b0ce79/blank.html
实际结果：原网页直接跳转到moz-extension://064ac6c9-374a-49b2-b407-a53683b0ce79/blank.html
附加说明：原来是按预期工作的，最近不知是升了浏览器版本还是扩展版本，就不好使了。只有选择“浏览器中打开”+确定才不会影响原网页，其他的操作都会导致原网页跳转

**Comment by yhnmj6666** [comment]
好的,谢谢反馈!下个版本可以修复
