### ISSUE TITLE
繁體語系支援

### ISSUE THREAD

**Issue by zhtw2013** [yhnmj6666/NewThunderCross#9]
[Strings.zh-TW.zip](https://github.com/yhnmj6666/NewThunderCross/files/1619348/Strings.zh-TW.zip)

用語轉換完成，希望作者能夠加入它！

AMO介紹。

相容FF57+的迅雷召喚工具

一個“使用迅雷下載”的下載工具

安裝完附加元件以後，需要從下面的下載位址下載 exe 檔案。將 exe 檔案放在某個位置，並按兩下exe 檔案。點選 yes 即可完成設定。（需要系統已安裝 .net 框架 4.6 版以上）

下載網址:

64 位元版本:
https://github.com/yhnmj6666/NewThunderCross/releases/download/v0.2.2/ThunderCross_x64.exe

32 位元版本(使用迅雷5和迷你迅雷的64位元使用者也請下載此版本):
https://github.com/yhnmj6666/NewThunderCross/releases/download/v0.2.2/ThunderCross_x86.exe

設定完成以後請不要移動 exe 檔案的位置。

如何移除：在已經安裝的狀態下按兩下 exe 檔案，點選 yes 即可。

PS:如果你想讓你用的下載工具得到支援，可以在評論裡留言！我會看情況加入支援（聞到了鴿的氣息)

**Comment by yhnmj6666** [comment]
感谢支持!我会加入它的!
